/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Interfaces.Absence.InterfacePrincipaleAbsence;
import Interfaces.Classe.InterfacePrincipaleClasse;
import Interfaces.Eleve.InterfacePrincipaleEleve;
import Interfaces.Emplois.InterfacePrincipaleEmplois;
import Interfaces.Instituteur.InterfacePrincipaleInstituteur;
import Interfaces.Note.InterfacePrincipaleNote;
import Interfaces.Parametres.Parametres;
import Interfaces.Salle.InterfacePrincipaleSalle;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Almia
 */
public class Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form Acceuil
     */
    public Acceuil() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        InterfacePrincipaleEleve GestEleve=new InterfacePrincipaleEleve();
        jPanel1.add(GestEleve);
        InterfacePrincipaleInstituteur GestInstituteur=new InterfacePrincipaleInstituteur();
        jPanel2.add(GestInstituteur);
        InterfacePrincipaleSalle GestSalle=new InterfacePrincipaleSalle();
        jPanel3.add(GestSalle);
        InterfacePrincipaleClasse GestClasse=new InterfacePrincipaleClasse();
        jPanel4.add(GestClasse);
        InterfacePrincipaleEmplois GestEmplois=new InterfacePrincipaleEmplois();
        jPanel5.add(GestEmplois);
        InterfacePrincipaleAbsence GestAbsence=new InterfacePrincipaleAbsence();
        jPanel6.add(GestAbsence);
        InterfacePrincipaleNote GestNote=new InterfacePrincipaleNote();
        jPanel7.add(GestNote);
        Parametres para=new Parametres();
        jPanel9.add(para);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 471));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(600, 38));
        jTabbedPane1.addTab("Gestion des élèves", jPanel1);
        jTabbedPane1.addTab("Gestion des Instituteurs", jPanel2);
        jTabbedPane1.addTab("Gestion des Salles", jPanel3);
        jTabbedPane1.addTab("Gestion des Classes", jPanel4);
        jTabbedPane1.addTab("Gestion des Emplois de Temps", jPanel5);
        jTabbedPane1.addTab("Gestion des Absences", jPanel6);
        jTabbedPane1.addTab("Gestion des Notes", jPanel7);
        jTabbedPane1.addTab("Gestion du Conseil et des PV", jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Parametres", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1071, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public JPanel getjPanel6() {
        return jPanel6;
    }

    public JPanel getjPanel7() {
        return jPanel7;
    }

    public JPanel getjPanel8() {
        return jPanel8;
    }

    public JPanel getjPanel9() {
        return jPanel9;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
