/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Absence;

import Entitées.Absence;
import Entitées.Classe;
import Entitées.Eleve;
import Plus.Conversion;
import java.sql.SQLException;
import java.time.Year;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Almia
 */
public class InterfacePrincipaleAbsence extends javax.swing.JPanel {

    /**
     * Creates new form InterfacePrincipaleAbsence
     */
    public final static void updateTableAb(){
        jComboBoxClasse.removeAllItems();
        jComboBoxClasse.addItem("Classe");
        Classe[] tabeC=new Classe[1000];
        tabeC=Classe.AfficherClasses();
        if(tabeC!=null){
        int i=0;
             while (i<tabeC.length){
             jComboBoxClasse.addItem(tabeC[i].getNom());
             i++;}
             
        }
        
        
    }
    
    public InterfacePrincipaleAbsence() {
        initComponents();
        updateTableAb();
        jTable1.setEnabled(false);jLabel1.setVisible(false);
        String[] jours=new String[] { "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"};
         jComboBoxMois.addActionListener((e) -> {
            int x=jComboBoxJours.getItemCount()-1;
             for(int j=0;j<x;j++)
             jComboBoxJours.removeItemAt(1);
            switch(jComboBoxMois.getSelectedIndex()){
                case 1:
                case 3:
                case 5:
                case 7:
                case 8:
                case 10:
                case 12:
                for(int i=0;i<jours.length;i++)
                    jComboBoxJours.addItem(jours[i]);
                break;
                case 4:
                case 6:
                case 9:
                case 11:
                for(int i=0;i<30;i++)
                    jComboBoxJours.addItem(jours[i]);
                break;
                case 2:
                    int annee = Year.now().getValue();
                    if( ((annee % 4 == 0) && !(annee % 100 == 0))    ||   (annee % 400 == 0)     )
                        for(int i=0;i<29;i++)
                           jComboBoxJours.addItem(jours[i]);
                    else for(int i=0;i<28;i++)
                           jComboBoxJours.addItem(jours[i]);
                break;
            }
        });      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonEnregistrer = new javax.swing.JButton();
        jButtonReinitialiser = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxClasse = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxJours = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMois = new javax.swing.JComboBox<>();
        jButtonConfirmer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM", "PRENOM", "8h-10h", "10h-12hl", "12h-13h", "13h-15h", "15h-17h"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerActionPerformed(evt);
            }
        });

        jButtonReinitialiser.setText("Reinitialiser");
        jButtonReinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReinitialiserActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Classe/Date"));

        jLabel2.setText("Classe");

        jComboBoxClasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classe" }));

        jLabel3.setText("Jours");

        jComboBoxJours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jours" }));

        jLabel4.setText("Mois");

        jComboBoxMois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mois", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juilet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre" }));

        jButtonConfirmer.setText("Confirmer");
        jButtonConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxClasse, javax.swing.GroupLayout.Alignment.LEADING, 0, 72, Short.MAX_VALUE)
                    .addComponent(jComboBoxJours, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxMois, 0, 1, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConfirmer)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxJours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButtonConfirmer)
                .addGap(45, 45, 45))
        );

        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Veuillez-entrer une date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonReinitialiser)
                .addGap(18, 18, 18)
                .addComponent(jButtonEnregistrer)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEnregistrer)
                    .addComponent(jButtonReinitialiser))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
        String a=jComboBoxJours.getSelectedItem().toString()+"+"+jComboBoxMois.getSelectedItem().toString();
        for(int i=0;i<model.getRowCount();i++)
             Absence.SupprimerAbsence((int)model.getValueAt(i, 0),a);
        for(int j=0;j<model.getRowCount();j++){
            Absence x=new Absence();
            int m=0;
            x.setEleve(Eleve.ChargerEleve((int)model.getValueAt(j, 0)));
            x.setDate(jComboBoxJours.getSelectedItem().toString()+"+"+jComboBoxMois.getSelectedItem().toString());
            String s="";
            for(int i=3;i<8;i++){
                if((boolean)model.getValueAt(j,i)==true)
                {s+=i-2;
                m++;}
                }
            x.setPeriode(s);
            if(m!=0){
                if(Absence.ChargerAbsence(x.getEleve().getId(),x.getPeriode())!=null)
                    x.ModifierAbsence(x.getEleve().getId(), x.getDate());
                else x.AjouterAbsence();
            }
            
        }
    }//GEN-LAST:event_jButtonEnregistrerActionPerformed

    private void jButtonReinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReinitialiserActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
        String a=jComboBoxJours.getSelectedItem().toString()+"+"+jComboBoxMois.getSelectedItem().toString();
        for(int i=0;i<model.getRowCount();i++)
             Absence.SupprimerAbsence((int)model.getValueAt(i, 0),a);
    }//GEN-LAST:event_jButtonReinitialiserActionPerformed

    private void jButtonConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmerActionPerformed
        // TODO add your handling code here:
        if(jComboBoxClasse.getSelectedIndex()==0){
            jLabel1.setText("Veuillez-selectionner la classe!");
            jLabel1.setVisible(true);}
        else if(jComboBoxJours.getSelectedIndex()==0 || jComboBoxMois.getSelectedIndex()==0){
            jLabel1.setText("Veuillez-specifier la date!");
            jLabel1.setVisible(true);}
        else jLabel1.setVisible(false);
        
        if(jLabel1.isVisible()==false){
            jTable1.setEnabled(true);
            Eleve tabe[]=new Eleve[30];
        Absence ab[]=new Absence[100];
        String o=jComboBoxJours.getSelectedItem().toString()+"+"+jComboBoxMois.getSelectedItem().toString();
        ab=Absence.AfficherAbsences(Classe.ChargerClasseParNom(jComboBoxClasse.getSelectedItem().toString()).getId(),o);
        tabe=Eleve.RechercherEleveParClasse(Classe.ChargerClasseParNom(jComboBoxClasse.getSelectedItem().toString()).getId());
        DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        if(tabe!=null){
            for(int i=0;i<tabe.length;i++){
                model.addRow(new Object[]{tabe[i].getId(),tabe[i].getNom(),tabe[i].getPrenom(),false,false,false,false,false});
                if(ab!=null){
                    try{
                     for(int j=0;j<ab.length;j++){
                         if(ab[j].getEleve().getId()==tabe[i].getId()){
                         String a=ab[j].getPeriode();
                         int k=0;
                          while(k<a.length()){
                          int b=Character.getNumericValue(a.charAt(k))+2;
                          model.setValueAt(true,i,b);
                          k++;}
                          break;
                         }
                      }}
                    catch(java.lang.NullPointerException e){}
                }
            }
            
            jTable1.setModel(model);}}

        
        
    }//GEN-LAST:event_jButtonConfirmerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmer;
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JButton jButtonReinitialiser;
    private static javax.swing.JComboBox<String> jComboBoxClasse;
    private static javax.swing.JComboBox<String> jComboBoxJours;
    private static javax.swing.JComboBox<String> jComboBoxMois;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
