/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Ecole;

import Plus.Conversion;
import Plus.Email;
import Plus.LengthRestrictedDocument;
import Entitées.Ecole;
import javax.swing.JOptionPane;

/**
 *
 * @author Almia
 */
public class SaisirInfos extends javax.swing.JPanel {

    /**
     * Creates new form SaisirInfos
     */
    public SaisirInfos() {
        initComponents();
        jTextFieldFax.setDocument(new LengthRestrictedDocument(10));
        jTextFieldCodePostal.setDocument(new LengthRestrictedDocument(4));
        jTextFieldNumTel.setDocument(new LengthRestrictedDocument(8));
        if(Ecole.ChargerEcole().getNom()!=null){
            Ecole x=Ecole.ChargerEcole();
            jTextFieldNom.setText(x.getNom());
            jTextFieldAdresse.setText(x.getAdresse());
            if(x.getCodePostal()!=0)
            jTextFieldCodePostal.setText(Integer.toString(x.getCodePostal()));
            jComboBoxVille.setSelectedItem(x.getVille());
            jTextFieldEmail.setText(x.getEmail());
            if(x.getFax()!=0)
            jTextFieldFax.setText(Integer.toString(x.getFax()));     
            jTextFieldNumTel.setText(Integer.toString(x.getTelephone()));
            jTextFieldSiteWeb.setText(x.getSiteWeb());
        }
        
        jLabel9.setVisible(false);jLabel10.setVisible(false);jLabel11.setVisible(false);jLabel12.setVisible(false);jLabel13.setVisible(false);jLabel14.setVisible(false);jLabel15.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxVille = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodePostal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSiteWeb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNumTel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldFax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonEnregistrer = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informations Ecole"));

        jLabel1.setText("Nom*");

        jLabel2.setText("Ville*");

        jComboBoxVille.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ville", "Ariana", "Béja", "Ben Arous", "Bizerte", "Gabès", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kébili", "La Manouba", "Le Kef", "Mahdia", "Médenine", "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliana", "Sousse", "Tataouine", "Tozeu", "Tunis", "Zaghouan" }));

        jLabel3.setText("Adresse*");

        jLabel4.setText("Code Postal");

        jTextFieldCodePostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodePostalKeyTyped(evt);
            }
        });

        jLabel5.setText("Site Web");

        jLabel6.setText("Num tel*");

        jTextFieldNumTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumTelKeyTyped(evt);
            }
        });

        jLabel7.setText("Fax");

        jTextFieldFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFaxKeyTyped(evt);
            }
        });

        jLabel8.setText("E-mail");

        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Erreur, champ vide");

        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setText("Veuillez-indiquer la ville");

        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("Erreur, champ vide");

        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("Code Postal invalide");

        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setText("jLabel13");

        jLabel14.setForeground(new java.awt.Color(255, 102, 102));
        jLabel14.setText("Fax invalide");

        jLabel15.setForeground(new java.awt.Color(255, 102, 102));
        jLabel15.setText("E-mail invalide");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSiteWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAdresse))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxVille, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumTel)
                            .addComponent(jTextFieldFax)
                            .addComponent(jTextFieldEmail))))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSiteWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEnregistrer)
                        .addGap(176, 176, 176))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEnregistrer)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodePostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodePostalKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodePostalKeyTyped

    private void jTextFieldNumTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumTelKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNumTelKeyTyped

    private void jTextFieldFaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFaxKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldFaxKeyTyped

    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerActionPerformed
        // TODO add your handling code here:
        if(jTextFieldNom.getText().equals(""))
            jLabel9.setVisible(true);
        else jLabel9.setVisible(false);
        
        if(jComboBoxVille.getSelectedIndex()==0)
            jLabel10.setVisible(true);
        else jLabel10.setVisible(false);
        
        if(jTextFieldAdresse.getText().equals("")){
            jLabel11.setVisible(true);
        }
        else jLabel11.setVisible(false);
        
        if(jTextFieldCodePostal.getText().length()<4 && !(jTextFieldCodePostal.getText()).equals(""))
            jLabel12.setVisible(true);
        else jLabel12.setVisible(false);
        
        if(jTextFieldNumTel.getText().equals("")){
            jLabel13.setText("Erreur, champ vide");
            jLabel13.setVisible(true);
        }
        else if(jTextFieldNumTel.getText().length()<8)
            {jLabel13.setText("Num Tel invalide");
            jLabel13.setVisible(true);}
        else jLabel13.setVisible(false);
        
        if(jTextFieldFax.getText().length()<10 && !(jTextFieldFax.getText()).equals(""))
            jLabel14.setVisible(true);
        else jLabel14.setVisible(false);
        
        if(!Email.isValidEmailAddress(jTextFieldEmail.getText())&& !(jTextFieldEmail.getText()).equals(""))
            jLabel15.setVisible(true);
        else jLabel15.setVisible(false);
        
        if(jLabel9.isVisible()==false && jLabel10.isVisible()==false && jLabel11.isVisible()==false && jLabel12.isVisible()==false && jLabel13.isVisible()==false && jLabel14.isVisible()==false && jLabel15.isVisible()==false){
            Ecole x=new Ecole();
            x.setNom(jTextFieldNom.getText());
            x.setAdresse(jTextFieldAdresse.getText());
            x.setCodePostal(Conversion.StringtoInt(jTextFieldCodePostal.getText()));
            x.setVille(jComboBoxVille.getSelectedItem().toString());
            x.setEmail(jTextFieldEmail.getText());
            x.setFax(Conversion.StringtoInt(jTextFieldFax.getText()));
            x.setTelephone(Conversion.StringtoInt(jTextFieldNumTel.getText()));
            x.setSiteWeb(jTextFieldSiteWeb.getText());
            if(Ecole.ChargerEcole().getNom()==null){
                if(x.SaisirInfo()){
                    JOptionPane.showMessageDialog(null, "Informations école enregistrés!");
                }
                else JOptionPane.showMessageDialog(null, "Echec enregistrement!");       
            }
            else {
                if(x.ModifierInfoEcole()){
                    JOptionPane.showMessageDialog(null, "Informations école enregistrés!");
                }
                else JOptionPane.showMessageDialog(null, "Echec enregistrement!");  
            }
        }
        
    }//GEN-LAST:event_jButtonEnregistrerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JComboBox<String> jComboBoxVille;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldCodePostal;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFax;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldNumTel;
    private javax.swing.JTextField jTextFieldSiteWeb;
    // End of variables declaration//GEN-END:variables
}
