/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Salle;

import Plus.Conversion;
import Plus.LengthRestrictedDocument;
import Entitées.Salle;
import Interfaces.Emplois.InterfacePrincipaleEmplois;
import static Interfaces.Salle.InterfacePrincipaleSalle.updateTableSalle;
import javax.swing.JOptionPane;

/**
 *
 * @author Almia
 */
public class AjouterSalle extends javax.swing.JFrame {

    /**
     * Creates new form AjouterSalle
     */
    public AjouterSalle() {       
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jTextFieldNom.setDocument(new LengthRestrictedDocument(20));
        jLabel4.setVisible(false);jLabel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNom = new javax.swing.JTextField();
        jComboBoxTYPE = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonANNULER = new javax.swing.JButton();
        jButtonREINITIALISER = new javax.swing.JButton();
        jButtonENREGISTRER = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldNom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jComboBoxTYPE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type", "Cours", "Sport", "Informtique", "Musique" }));

        jLabel2.setText("Type  *");

        jLabel1.setText(" Nom  *");

        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Erreur,champ vide");

        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Veiillez-indiquer le Type");

        jButtonANNULER.setText("Annuler");
        jButtonANNULER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonANNULERActionPerformed(evt);
            }
        });

        jButtonREINITIALISER.setText("Réinistialiser");
        jButtonREINITIALISER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREINITIALISERActionPerformed(evt);
            }
        });

        jButtonENREGISTRER.setText("Enregistrer");
        jButtonENREGISTRER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENREGISTRERActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonANNULER)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonREINITIALISER)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonENREGISTRER))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTYPE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTYPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonREINITIALISER)
                    .addComponent(jButtonENREGISTRER)
                    .addComponent(jButtonANNULER))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonANNULERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonANNULERActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment Quitter ?","Attention",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            dispose();
        }
    }//GEN-LAST:event_jButtonANNULERActionPerformed

    private void jButtonREINITIALISERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREINITIALISERActionPerformed
        // TODO add your handling code here:
        jLabel4.setVisible(false);  jLabel3.setVisible(false);
        jTextFieldNom.setText("");
        jComboBoxTYPE.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonREINITIALISERActionPerformed

    private void jButtonENREGISTRERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENREGISTRERActionPerformed
        // TODO add your handling code here:
        
        if( jComboBoxTYPE.getSelectedIndex()==0){
            jLabel3.setVisible(true);
        }
        else jLabel3.setVisible(false);
       
        if(jTextFieldNom.getText().equals("")){
            jLabel4.setText("Erreur, champ vide");
            jLabel4.setVisible(true);
        }
        else if(Salle.RechercherSalleParNom(jTextFieldNom.getText()).getNom()!=null){
            jLabel4.setText("Nom invalide");
            jLabel4.setVisible(true);
            JOptionPane.showMessageDialog(null, "Une salle avec le meme nom existe!");
        }
        else jLabel4.setVisible(false);
        

        if(jLabel4.isVisible()==false &&  jLabel3.isVisible()== false){
            Salle S;
            S = new Salle();
            S.setNom(jTextFieldNom.getText());
            S.setType(jComboBoxTYPE.getSelectedItem().toString());
            if(S.AjouterSalle()){
                JOptionPane.showMessageDialog(null, "La salle a été ajouté avec succes!");
                dispose();
                InterfacePrincipaleSalle.updateTableSalle();
                InterfacePrincipaleEmplois.updateEmplois();

            }
            else JOptionPane.showMessageDialog(null, "Echec d'ajout");

        }
    }//GEN-LAST:event_jButtonENREGISTRERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterSalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonANNULER;
    private javax.swing.JButton jButtonENREGISTRER;
    private javax.swing.JButton jButtonREINITIALISER;
    private javax.swing.JComboBox<String> jComboBoxTYPE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables
}
