/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Parametres;

import Interfaces.Ecole.SaisirInfos;
import Interfaces.Matiere.InterfacePrincipaleMatiere;
import Interfaces.User.InterfacePrincipaleUser;

/**
 *
 * @author Almia
 */
public class Parametres extends javax.swing.JPanel {

    /**
     * Creates new form Parametres
     */
    public Parametres() {
        initComponents();
        SaisirInfos Ecole=new SaisirInfos();
        InfosEcole.add(Ecole);
        InterfacePrincipaleMatiere Matiere=new InterfacePrincipaleMatiere();
        GestMatieres.add(Matiere);
        InterfacePrincipaleUser Utilisateur=new InterfacePrincipaleUser();
        GestUtilisateurs.add(Utilisateur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        InfosEcole = new javax.swing.JPanel();
        GestMatieres = new javax.swing.JPanel();
        GestUtilisateurs = new javax.swing.JPanel();

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane1.addTab("Informations Ecole", InfosEcole);
        jTabbedPane1.addTab("Gestion Matières", GestMatieres);
        jTabbedPane1.addTab("Gestion Utilisateurs", GestUtilisateurs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GestMatieres;
    private javax.swing.JPanel GestUtilisateurs;
    private javax.swing.JPanel InfosEcole;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
