/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Eleve;
import Plus.Email;
import Interfaces.Eleve.InterfacePrincipaleEleve;
import Plus.LengthRestrictedDocument;
import javax.swing.JOptionPane;
import Entitées.Eleve;
import Plus.Conversion;
import javax.swing.ComboBoxModel;
import javax.swing.event.ListDataListener;
/**
 *
 * @author Almia
 */
public class AjouterEleve extends javax.swing.JFrame {

    /**
     * Creates new form AjouterEleve
     */
    public AjouterEleve() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        String[] jours=new String[] { "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"};
        jTextFieldNCIN.setDocument(new LengthRestrictedDocument(8));
        jTextFieldCODEPOSTAL.setDocument(new LengthRestrictedDocument(4));
        jTextFieldCODEPOSTALRES.setDocument(new LengthRestrictedDocument(4));
        jTextFieldNUMTEL.setDocument(new LengthRestrictedDocument(8));
        jLabel18.setVisible(false);jLabel19.setVisible(false);jLabel20.setVisible(false);jLabel21.setVisible(false);jLabel22.setVisible(false);jLabel23.setVisible(false);jLabel24.setVisible(false);jLabel25.setVisible(false);jLabel26.setVisible(false);jLabel27.setVisible(false);jLabel28.setVisible(false);jLabel29.setVisible(false);jLabel30.setVisible(false);
        jLabel31.setVisible(false);jLabel32.setVisible(false);jLabel33.setVisible(false);
        jComboBoxMOIS.addActionListener((e) -> {
            if(jComboBoxANNEE.getSelectedIndex()!=0){
            int x=jComboBoxJOUR.getItemCount()-1;
             for(int j=0;j<x;j++)
             jComboBoxJOUR.removeItemAt(1);
            switch(jComboBoxMOIS.getSelectedIndex()){
                case 1:
                case 3:
                case 5:
                case 7:
                case 8:
                case 10:
                case 12:
                for(int i=0;i<jours.length;i++)
                    jComboBoxJOUR.addItem(jours[i]);
                break;
                case 4:
                case 6:
                case 9:
                case 11:
                for(int i=0;i<30;i++)
                    jComboBoxJOUR.addItem(jours[i]);
                break;
                case 2:
                    int annee=Conversion.StringtoInt(jComboBoxANNEE.getSelectedItem().toString());
                    if( ((annee % 4 == 0) && !(annee % 100 == 0))    ||   (annee % 400 == 0)     )
                        for(int i=0;i<29;i++)
                           jComboBoxJOUR.addItem(jours[i]);
                    else for(int i=0;i<28;i++)
                           jComboBoxJOUR.addItem(jours[i]);
                break;
            }}
        });
        jComboBoxANNEE.addActionListener((e) -> {
            if(jComboBoxMOIS.getSelectedIndex()!=0){
            int x=jComboBoxJOUR.getItemCount()-1;
             for(int j=0;j<x;j++)
             jComboBoxJOUR.removeItemAt(1);
            switch(jComboBoxMOIS.getSelectedIndex()){
                case 1:
                case 3:
                case 5:
                case 7:
                case 8:
                case 10:
                case 12:
                for(int i=0;i<jours.length;i++)
                    jComboBoxJOUR.addItem(jours[i]);
                break;
                case 4:
                case 6:
                case 9:
                case 11:
                for(int i=0;i<30;i++)
                    jComboBoxJOUR.addItem(jours[i]);
                break;
                case 2:
                    int annee=Conversion.StringtoInt(jComboBoxANNEE.getSelectedItem().toString());
                    if( ((annee % 4 == 0) && !(annee % 100 == 0))    ||   (annee % 400 == 0)     )
                        for(int i=0;i<29;i++)
                           jComboBoxJOUR.addItem(jours[i]);
                    else for(int i=0;i<28;i++)
                           jComboBoxJOUR.addItem(jours[i]);
                break;
            }}
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNOM = new javax.swing.JTextField();
        jTextFieldPRENOM = new javax.swing.JTextField();
        jTextFieldADRESSE = new javax.swing.JTextField();
        jTextFieldCODEPOSTAL = new javax.swing.JTextField();
        jComboBoxANNEE = new javax.swing.JComboBox<>();
        jComboBoxMOIS = new javax.swing.JComboBox<>();
        jComboBoxJOUR = new javax.swing.JComboBox<>();
        jComboBoxNIVEAU = new javax.swing.JComboBox<>();
        jComboBoxPAYS = new javax.swing.JComboBox<>();
        jComboBoxVILLE = new javax.swing.JComboBox<>();
        jComboBoxSEXE = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldNOMRES = new javax.swing.JTextField();
        jTextFieldPRENOMRES = new javax.swing.JTextField();
        jTextFieldADRESSERES = new javax.swing.JTextField();
        jTextFieldNUMTEL = new javax.swing.JTextField();
        jTextFieldEMAIL = new javax.swing.JTextField();
        jTextFieldCODEPOSTALRES = new javax.swing.JTextField();
        jTextFieldPROFESSION = new javax.swing.JTextField();
        jTextFieldRELATION = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldNCIN = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButtonREINITIALISER = new javax.swing.JButton();
        jButtonENREGISTRER = new javax.swing.JButton();
        jButtonANNULER = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Informations élève", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("Nom *");

        jLabel2.setText("Date de Naissance *");

        jLabel3.setText("Prenom *");

        jLabel4.setText("Code Postal");

        jLabel5.setText("Sexe *");

        jLabel6.setText("Niveau *");

        jLabel7.setText("Adresse *");

        jLabel10.setText("Pays*");

        jLabel11.setText("Ville");

        jTextFieldNOM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNOMKeyTyped(evt);
            }
        });

        jTextFieldPRENOM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPRENOMKeyTyped(evt);
            }
        });

        jTextFieldCODEPOSTAL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCODEPOSTALKeyTyped(evt);
            }
        });

        jComboBoxANNEE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Année", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        jComboBoxMOIS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mois", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juilet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre" }));

        jComboBoxJOUR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jour" }));

        jComboBoxNIVEAU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niveau", "1ère", "2ème", "3ème", "4ème", "5ème", "6ème" }));

        jComboBoxPAYS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pays", "Tunisia" }));

        jComboBoxVILLE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ville", "Ariana", "Béja", "Ben Arous", "Bizerte", "Gabès", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kébili", "La Manouba", "Le Kef", "Mahdia", "Médenine", "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliana", "Sousse", "Tataouine", "Tozeu", "Tunis", "Zaghouan" }));

        jComboBoxSEXE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexe", "Homme", "Femme" }));

        jLabel18.setForeground(new java.awt.Color(255, 102, 102));
        jLabel18.setText("Erreur,champ vide");

        jLabel19.setForeground(new java.awt.Color(255, 102, 102));
        jLabel19.setText("Erreur,champ vide");

        jLabel20.setForeground(new java.awt.Color(255, 102, 102));
        jLabel20.setText("Veuillez indiquer le sexe");

        jLabel21.setForeground(new java.awt.Color(255, 102, 102));
        jLabel21.setText("Veeuillez indiquer le niveau");

        jLabel22.setForeground(new java.awt.Color(255, 102, 102));
        jLabel22.setText("Veuillez indiquer le pays");

        jLabel23.setForeground(new java.awt.Color(255, 102, 102));
        jLabel23.setText("Erreur,champ vide");

        jLabel30.setForeground(new java.awt.Color(255, 102, 102));
        jLabel30.setText("Veuillez indiquer la Date de naissance");

        jLabel31.setForeground(new java.awt.Color(255, 102, 102));
        jLabel31.setText("Code Postal invalide");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxPAYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel22))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxSEXE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(jTextFieldNOM, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldADRESSE, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCODEPOSTAL, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPRENOM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel31)))
                            .addComponent(jComboBoxVILLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxNIVEAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(jComboBoxANNEE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxMOIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxJOUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPRENOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxANNEE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMOIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxJOUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxNIVEAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSEXE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxVILLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPAYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldADRESSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCODEPOSTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel31))
                .addGap(26, 26, 26))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Responsable Légal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel8.setText("Nom *");

        jLabel9.setText("Prenom *");

        jLabel12.setText("Prefession ");

        jLabel13.setText("Relation *");

        jLabel14.setText("Adresse *");

        jLabel15.setText("Code Postal");

        jLabel16.setText("Num tel *");

        jLabel17.setText("E-Mail ");

        jTextFieldNOMRES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNOMRESKeyTyped(evt);
            }
        });

        jTextFieldPRENOMRES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPRENOMRESKeyTyped(evt);
            }
        });

        jTextFieldNUMTEL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNUMTELKeyTyped(evt);
            }
        });

        jTextFieldCODEPOSTALRES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCODEPOSTALRESKeyTyped(evt);
            }
        });

        jTextFieldPROFESSION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPROFESSIONKeyTyped(evt);
            }
        });

        jTextFieldRELATION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRELATIONKeyTyped(evt);
            }
        });

        jLabel36.setText("N°CIN *");

        jTextFieldNCIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNCINKeyTyped(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(255, 102, 102));
        jLabel24.setText("Erreur,champ vide");

        jLabel25.setForeground(new java.awt.Color(255, 102, 102));
        jLabel25.setText("Erreur,champ vide");

        jLabel26.setForeground(new java.awt.Color(255, 102, 102));
        jLabel26.setText("Erreur,champ vide");

        jLabel27.setForeground(new java.awt.Color(255, 102, 102));
        jLabel27.setText("Erreur,champ vide");

        jLabel28.setForeground(new java.awt.Color(255, 102, 102));
        jLabel28.setText("Erreur,champ vide");

        jLabel29.setForeground(new java.awt.Color(255, 102, 102));
        jLabel29.setText("Erreur,champ vide");

        jLabel32.setForeground(new java.awt.Color(255, 102, 102));
        jLabel32.setText("Code Postal invalide");

        jLabel33.setForeground(new java.awt.Color(255, 102, 102));
        jLabel33.setText("E-mail invalide");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel36))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldNOMRES, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNCIN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPROFESSION)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldADRESSERES, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNUMTEL, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCODEPOSTALRES)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(17, 17, 17)
                            .addComponent(jTextFieldRELATION, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldPRENOMRES, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel32)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(29, 29, 29)))
                .addGap(90, 90, 90))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTextFieldNCIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNOMRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPRENOMRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldPROFESSION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRELATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldADRESSERES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCODEPOSTALRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jTextFieldNUMTEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29))
                    .addComponent(jLabel33))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButtonREINITIALISER.setText("Réinitialiser");
        jButtonREINITIALISER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREINITIALISERActionPerformed(evt);
            }
        });

        jButtonENREGISTRER.setText("Enregistrer");
        jButtonENREGISTRER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENREGISTRERActionPerformed(evt);
            }
        });

        jButtonANNULER.setText("Annuler");
        jButtonANNULER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonANNULERActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonANNULER)
                .addGap(18, 18, 18)
                .addComponent(jButtonREINITIALISER)
                .addGap(18, 18, 18)
                .addComponent(jButtonENREGISTRER)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonREINITIALISER)
                    .addComponent(jButtonENREGISTRER)
                    .addComponent(jButtonANNULER))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPRENOMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPRENOMKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPRENOMKeyTyped

    private void jTextFieldNOMRESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNOMRESKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNOMRESKeyTyped

    private void jTextFieldPRENOMRESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPRENOMRESKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPRENOMRESKeyTyped

    private void jTextFieldRELATIONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRELATIONKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldRELATIONKeyTyped

    private void jTextFieldPROFESSIONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPROFESSIONKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPROFESSIONKeyTyped

    private void jTextFieldCODEPOSTALKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCODEPOSTALKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCODEPOSTALKeyTyped

    private void jTextFieldNCINKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNCINKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNCINKeyTyped

    private void jTextFieldCODEPOSTALRESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCODEPOSTALRESKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCODEPOSTALRESKeyTyped

    private void jTextFieldNUMTELKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNUMTELKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNUMTELKeyTyped

    private void jButtonREINITIALISERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREINITIALISERActionPerformed
        // TODO add your handling code here:
        jLabel18.setVisible(false);jLabel19.setVisible(false);jLabel20.setVisible(false);jLabel21.setVisible(false);jLabel22.setVisible(false);jLabel23.setVisible(false);jLabel24.setVisible(false);jLabel25.setVisible(false);jLabel26.setVisible(false);jLabel27.setVisible(false);jLabel28.setVisible(false);jLabel29.setVisible(false);jLabel30.setVisible(false);jLabel31.setVisible(false);jLabel32.setVisible(false);jLabel33.setVisible(false);
        jTextFieldNOM.setText("");jTextFieldPRENOM.setText("");jTextFieldADRESSE.setText("");jTextFieldCODEPOSTAL.setText("");jTextFieldNOMRES.setText("");jTextFieldPRENOMRES.setText("");jTextFieldADRESSERES.setText("");jTextFieldNUMTEL.setText("");jTextFieldEMAIL.setText("");jTextFieldCODEPOSTALRES.setText("");jTextFieldPROFESSION.setText("");jTextFieldRELATION.setText("");jTextFieldNCIN.setText("");
        jComboBoxANNEE.setSelectedIndex(0);jComboBoxMOIS.setSelectedIndex(0);jComboBoxJOUR.setSelectedIndex(0);jComboBoxNIVEAU.setSelectedIndex(0);jComboBoxPAYS.setSelectedIndex(0);jComboBoxVILLE.setSelectedIndex(0);jComboBoxSEXE.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonREINITIALISERActionPerformed

    private void jButtonANNULERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonANNULERActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment Quitter ?","Attention",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
		   {
			   dispose();
		   }
    }//GEN-LAST:event_jButtonANNULERActionPerformed

    private void jButtonENREGISTRERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENREGISTRERActionPerformed
        // TODO add your handling code here:
        if(jTextFieldNOM.getText().equals("")){
            jLabel18.setVisible(true);
        }
        else jLabel18.setVisible(false);
        
        if(jTextFieldPRENOM.getText().equals("")){
            jLabel19.setVisible(true);
        }
        else jLabel19.setVisible(false);
        
        if(jTextFieldADRESSE.getText().equals("")){
            jLabel23.setVisible(true);
        }
        else jLabel23.setVisible(false);
        
        if(jTextFieldCODEPOSTAL.getText().length()<4 && !(jTextFieldCODEPOSTAL.getText()).equals(""))
            jLabel31.setVisible(true);
        else jLabel31.setVisible(false);
        
        if(jTextFieldNCIN.getText().equals("")){
            jLabel24.setText("Erreur, champ vide");
            jLabel24.setVisible(true);
        }
        else if(jTextFieldNCIN.getText().length()<8)
            {jLabel24.setText("N°CIN Invalide");
            jLabel24.setVisible(true);}
        else jLabel24.setVisible(false);
        
        if(jTextFieldNOMRES.getText().equals("")){
            jLabel25.setVisible(true);
        }
        else jLabel25.setVisible(false);
        
        if(jTextFieldPRENOMRES.getText().equals("")){
            jLabel26.setVisible(true);
        }
        else jLabel26.setVisible(false);
        
        if(jTextFieldRELATION.getText().equals("")){
            jLabel27.setVisible(true);
        }
        else jLabel27.setVisible(false);
        
        if(jTextFieldADRESSERES.getText().equals("")){
            jLabel28.setVisible(true);
        }
        else jLabel28.setVisible(false);
        
        if(jTextFieldCODEPOSTALRES.getText().length()<4 && !(jTextFieldCODEPOSTALRES.getText()).equals(""))
            jLabel32.setVisible(true);
        else jLabel32.setVisible(false);
        
        if(!Email.isValidEmailAddress(jTextFieldEMAIL.getText())&& !(jTextFieldEMAIL.getText()).equals(""))
            jLabel33.setVisible(true);
        else jLabel33.setVisible(false);
        
        if(jTextFieldNUMTEL.getText().equals("")){
            jLabel29.setText("Erreur, champ vide");
            jLabel29.setVisible(true);
        }
        else if(jTextFieldNUMTEL.getText().length()<8)
            {jLabel29.setText("Num Tel invalide");
            jLabel29.setVisible(true);}
        else jLabel29.setVisible(false);
        
        if(jComboBoxANNEE.getSelectedIndex()==0 || jComboBoxMOIS.getSelectedIndex()==0 || jComboBoxJOUR.getSelectedIndex()==0){
            jLabel30.setVisible(true);
        }
        else jLabel30.setVisible(false);
        
        if(jComboBoxPAYS.getSelectedIndex()==0){
            jLabel22.setVisible(true);
        }
        else jLabel22.setVisible(false);
        
        if(jComboBoxNIVEAU.getSelectedIndex()==0){
            jLabel21.setVisible(true);
        }
        else jLabel21.setVisible(false);
        
        if(jComboBoxSEXE.getSelectedIndex()==0){
            jLabel20.setVisible(true);
        }
        else jLabel20.setVisible(false);
        
        if(jLabel18.isVisible()==false && jLabel19.isVisible()==false && jLabel20.isVisible()==false && jLabel21.isVisible()==false && jLabel22.isVisible()==false && jLabel23.isVisible()==false && jLabel24.isVisible()==false && jLabel25.isVisible()==false && jLabel26.isVisible()==false && jLabel27.isVisible()==false && jLabel28.isVisible()==false && jLabel29.isVisible()==false && jLabel30.isVisible()==false && jLabel31.isVisible()==false && jLabel32.isVisible()==false && jLabel33.isVisible()==false){
            Eleve e;
            e = new Eleve(8,jTextFieldNOM.getText(),jTextFieldPRENOM.getText(),jComboBoxANNEE.getSelectedItem().toString()+"+"+jComboBoxMOIS.getSelectedItem().toString()+"+"+jComboBoxJOUR.getSelectedItem().toString(),jComboBoxSEXE.getSelectedItem().toString(),jComboBoxPAYS.getSelectedItem().toString(),jComboBoxVILLE.getSelectedItem().toString(),jTextFieldADRESSE.getText(),Conversion.StringtoInt(jTextFieldCODEPOSTAL.getText()),jComboBoxNIVEAU.getSelectedItem().toString(),Conversion.StringtoInt(jTextFieldNCIN.getText()),jTextFieldNOMRES.getText(),jTextFieldPRENOMRES.getText(),jTextFieldPROFESSION.getText(),jTextFieldRELATION.getText(),jTextFieldADRESSERES.getText(),Conversion.StringtoInt(jTextFieldCODEPOSTALRES.getText()),Conversion.StringtoInt(jTextFieldNUMTEL.getText()),jTextFieldEMAIL.getText());
            if(e.AjouterEleve()){
                JOptionPane.showMessageDialog(null, "L'élève a été ajouté avec succes!");
                dispose();
                InterfacePrincipaleEleve.updateTableEl();
                
                
            }
            else JOptionPane.showMessageDialog(null, "Echec d'ajout d'élève!");
                
        }
    }//GEN-LAST:event_jButtonENREGISTRERActionPerformed

    private void jTextFieldNOMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNOMKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNOMKeyTyped
    
    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AjouterEleve().setVisible(true);
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonANNULER;
    private javax.swing.JButton jButtonENREGISTRER;
    private javax.swing.JButton jButtonREINITIALISER;
    private javax.swing.JComboBox<String> jComboBoxANNEE;
    private javax.swing.JComboBox<String> jComboBoxJOUR;
    private javax.swing.JComboBox<String> jComboBoxMOIS;
    private javax.swing.JComboBox<String> jComboBoxNIVEAU;
    private javax.swing.JComboBox<String> jComboBoxPAYS;
    private javax.swing.JComboBox<String> jComboBoxSEXE;
    private javax.swing.JComboBox<String> jComboBoxVILLE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldADRESSE;
    private javax.swing.JTextField jTextFieldADRESSERES;
    private javax.swing.JTextField jTextFieldCODEPOSTAL;
    private javax.swing.JTextField jTextFieldCODEPOSTALRES;
    private javax.swing.JTextField jTextFieldEMAIL;
    private javax.swing.JTextField jTextFieldNCIN;
    private javax.swing.JTextField jTextFieldNOM;
    private javax.swing.JTextField jTextFieldNOMRES;
    private javax.swing.JTextField jTextFieldNUMTEL;
    private javax.swing.JTextField jTextFieldPRENOM;
    private javax.swing.JTextField jTextFieldPRENOMRES;
    private javax.swing.JTextField jTextFieldPROFESSION;
    private javax.swing.JTextField jTextFieldRELATION;
    // End of variables declaration//GEN-END:variables
}
