/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Eleve;
import Plus.Conversion;
import Plus.Email;
import Plus.LengthRestrictedDocument;
import Entitées.Eleve;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Almia
 */
public class ModifierEleve extends javax.swing.JFrame {

    /**
     * Creates new form ModifierEleve
     */
    private int Ndoss;

    public int getNdoss() {
        return Ndoss;
    }

    public void setNdoss(int Ndoss) {
        this.Ndoss = Ndoss;
    }
    
    public ModifierEleve() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jTextFieldNCINRES.setDocument(new LengthRestrictedDocument(8));
        jTextFieldNUMTEL.setDocument(new LengthRestrictedDocument(8));
        jTextFieldCODEPOSTAL.setDocument(new LengthRestrictedDocument(4));
        jTextFieldCODEPOSTALRES.setDocument(new LengthRestrictedDocument(4));
        jLabelNom.setVisible(false);jLabelPrenom.setVisible(false);jLabelSexe.setVisible(false);jLabelDate.setVisible(false);
        jLabelPays.setVisible(false);jLabelAdresse.setVisible(false);jLabelNiveau.setVisible(false);
        jLabelNCIN.setVisible(false);jLabelNomRes.setVisible(false);jLabelAdrRes.setVisible(false);
        jLabelNum.setVisible(false);jLabelRelation.setVisible(false);jLabelPrenomRes.setVisible(false);
        jLabelCodePREs.setVisible(false);jLabelEmail.setVisible(false);jLabelCodeP.setVisible(false);        
        String[] jours=new String[] { "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"};
         jComboBoxMOIS.addActionListener((e) -> {
            if(jComboBoxANNEE.getSelectedIndex()!=0){
            int x=jComboBoxJOUR.getItemCount()-1;
             for(int j=0;j<x;j++)
             jComboBoxJOUR.removeItemAt(1);
            switch(jComboBoxMOIS.getSelectedIndex()){
                case 1:
                case 3:
                case 5:
                case 7:
                case 8:
                case 10:
                case 12:
                for(int i=0;i<jours.length;i++)
                    jComboBoxJOUR.addItem(jours[i]);
                break;
                case 4:
                case 6:
                case 9:
                case 11:
                for(int i=0;i<30;i++)
                    jComboBoxJOUR.addItem(jours[i]);
                break;
                case 2:
                    int annee=Conversion.StringtoInt(jComboBoxANNEE.getSelectedItem().toString());
                    if( ((annee % 4 == 0) && !(annee % 100 == 0))    ||   (annee % 400 == 0)     )
                        for(int i=0;i<29;i++)
                           jComboBoxJOUR.addItem(jours[i]);
                    else for(int i=0;i<28;i++)
                           jComboBoxJOUR.addItem(jours[i]);
                break;
            }}
        });
        jComboBoxANNEE.addActionListener((e) -> {
            if(jComboBoxMOIS.getSelectedIndex()!=0){
            int x=jComboBoxJOUR.getItemCount()-1;
             for(int j=0;j<x;j++)
             jComboBoxJOUR.removeItemAt(1);
            switch(jComboBoxMOIS.getSelectedIndex()){
                case 1:
                case 3:
                case 5:
                case 7:
                case 8:
                case 10:
                case 12:
                for(int i=0;i<jours.length;i++)
                    jComboBoxJOUR.addItem(jours[i]);
                break;
                case 4:
                case 6:
                case 9:
                case 11:
                for(int i=0;i<30;i++)
                    jComboBoxJOUR.addItem(jours[i]);
                break;
                case 2:
                    int annee=Conversion.StringtoInt(jComboBoxANNEE.getSelectedItem().toString());
                    if( ((annee % 4 == 0) && !(annee % 100 == 0))    ||   (annee % 400 == 0)     )
                        for(int i=0;i<29;i++)
                           jComboBoxJOUR.addItem(jours[i]);
                    else for(int i=0;i<28;i++)
                           jComboBoxJOUR.addItem(jours[i]);
                break;
            }}
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNOM = new javax.swing.JTextField();
        jTextFieldPRENOM = new javax.swing.JTextField();
        jTextFieldADRESSE = new javax.swing.JTextField();
        jTextFieldCODEPOSTAL = new javax.swing.JTextField();
        jComboBoxANNEE = new javax.swing.JComboBox<>();
        jComboBoxMOIS = new javax.swing.JComboBox<>();
        jComboBoxJOUR = new javax.swing.JComboBox<>();
        jComboBoxNIVEAU = new javax.swing.JComboBox<>();
        jComboBoxPAYS = new javax.swing.JComboBox<>();
        jComboBoxVILLE = new javax.swing.JComboBox<>();
        jComboBoxsexe = new javax.swing.JComboBox<>();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelSexe = new javax.swing.JLabel();
        jLabelNiveau = new javax.swing.JLabel();
        jLabelPays = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelCodeP = new javax.swing.JLabel();
        jButtonANNULER = new javax.swing.JButton();
        jButtonREINITIALISER = new javax.swing.JButton();
        jButtonENREGISTRER = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldNOMRES = new javax.swing.JTextField();
        jTextFieldPRENOMRES = new javax.swing.JTextField();
        jTextFieldADRESSERES = new javax.swing.JTextField();
        jTextFieldNUMTEL = new javax.swing.JTextField();
        jTextFieldEMAIL = new javax.swing.JTextField();
        jTextFieldCODEPOSTALRES = new javax.swing.JTextField();
        jTextFieldPROFESSIONRES = new javax.swing.JTextField();
        jTextFieldRELATION = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldNCINRES = new javax.swing.JTextField();
        jLabelNCIN = new javax.swing.JLabel();
        jLabelNomRes = new javax.swing.JLabel();
        jLabelAdrRes = new javax.swing.JLabel();
        jLabelNum = new javax.swing.JLabel();
        jLabelPrenomRes = new javax.swing.JLabel();
        jLabelRelation = new javax.swing.JLabel();
        jLabelCodePREs = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Informations élève", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("Nom *");

        jLabel2.setText("Date de Naissance *");

        jLabel3.setText("Prenom *");

        jLabel4.setText("Code Postal");

        jLabel5.setText("Sexe *");

        jLabel6.setText("Niveau *");

        jLabel7.setText("Adresse *");

        jLabel10.setText("Pays*");

        jLabel11.setText("Ville");

        jTextFieldNOM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNOMKeyTyped(evt);
            }
        });

        jTextFieldPRENOM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPRENOMKeyTyped(evt);
            }
        });

        jTextFieldADRESSE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldADRESSEKeyTyped(evt);
            }
        });

        jTextFieldCODEPOSTAL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCODEPOSTALKeyTyped(evt);
            }
        });

        jComboBoxANNEE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Année", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        jComboBoxMOIS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mois", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juilet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre" }));

        jComboBoxJOUR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jour", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29" }));

        jComboBoxNIVEAU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niveau", "1ère", "2ème", "3ème", "4ème", "5ème", "6ème" }));

        jComboBoxPAYS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pays", "Tunisia" }));

        jComboBoxVILLE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ville", "Ariana", "Béja", "Ben Arous", "Bizerte", "Gabès", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kébili", "La Manouba", "Le Kef", "Mahdia", "Médenine", "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliana", "Sousse", "Tataouine", "Tozeu", "Tunis", "Zaghouan" }));

        jComboBoxsexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexe", "Homme", "Femme" }));

        jLabelNom.setForeground(new java.awt.Color(255, 102, 102));
        jLabelNom.setText("Erreur,champ vide");

        jLabelPrenom.setForeground(new java.awt.Color(255, 102, 102));
        jLabelPrenom.setText("Erreur,champ vide");

        jLabelDate.setForeground(new java.awt.Color(255, 102, 102));
        jLabelDate.setText("Veuillez indiquer la Date de naissance");

        jLabelSexe.setForeground(new java.awt.Color(255, 102, 102));
        jLabelSexe.setText("Veuillez indiquer le sexe");

        jLabelNiveau.setForeground(new java.awt.Color(255, 102, 102));
        jLabelNiveau.setText("Veeuillez indiquer le niveau");

        jLabelPays.setForeground(new java.awt.Color(255, 102, 102));
        jLabelPays.setText("Veuillez indiquer le pays");

        jLabelAdresse.setForeground(new java.awt.Color(255, 102, 102));
        jLabelAdresse.setText("Erreur,champ vide");

        jLabelCodeP.setForeground(new java.awt.Color(255, 102, 102));
        jLabelCodeP.setText("Code Postal invalide");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxsexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelSexe))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxPAYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelPays, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(jTextFieldNOM, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNom))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldADRESSE, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelAdresse)))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jTextFieldPRENOM, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelPrenom))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldCODEPOSTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelCodeP))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxNIVEAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelNiveau))
                                    .addComponent(jComboBoxVILLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(jComboBoxANNEE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxMOIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxJOUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDate)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPRENOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom)
                    .addComponent(jLabelPrenom))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxANNEE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMOIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxJOUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDate))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxNIVEAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxsexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexe)
                    .addComponent(jLabelNiveau))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxVILLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPAYS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPays))
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldADRESSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCODEPOSTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdresse)
                    .addComponent(jLabelCodeP))
                .addGap(26, 26, 26))
        );

        jButtonANNULER.setText("Annuler");
        jButtonANNULER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonANNULERActionPerformed(evt);
            }
        });

        jButtonREINITIALISER.setText("Réinitialiser");
        jButtonREINITIALISER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREINITIALISERActionPerformed(evt);
            }
        });

        jButtonENREGISTRER.setText("Enregistrer");
        jButtonENREGISTRER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENREGISTRERActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Responsable Légal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel8.setText("Nom *");

        jLabel9.setText("Prenom *");

        jLabel12.setText("Prefession ");

        jLabel13.setText("Relation *");

        jLabel14.setText("Adresse *");

        jLabel15.setText("Code Postal");

        jLabel16.setText("Num tel *");

        jLabel17.setText("E-Mail ");

        jTextFieldNOMRES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNOMRESKeyTyped(evt);
            }
        });

        jTextFieldPRENOMRES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPRENOMRESKeyTyped(evt);
            }
        });

        jTextFieldNUMTEL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNUMTELKeyTyped(evt);
            }
        });

        jTextFieldCODEPOSTALRES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCODEPOSTALRESKeyTyped(evt);
            }
        });

        jTextFieldPROFESSIONRES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPROFESSIONRESKeyTyped(evt);
            }
        });

        jTextFieldRELATION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRELATIONKeyTyped(evt);
            }
        });

        jLabel36.setText("N°CIN *");

        jTextFieldNCINRES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNCINRESKeyTyped(evt);
            }
        });

        jLabelNCIN.setForeground(new java.awt.Color(255, 102, 102));
        jLabelNCIN.setText("Erreur,champ vide");

        jLabelNomRes.setForeground(new java.awt.Color(255, 102, 102));
        jLabelNomRes.setText("Erreur,champ vide");

        jLabelAdrRes.setForeground(new java.awt.Color(255, 102, 102));
        jLabelAdrRes.setText("Erreur,champ vide");

        jLabelNum.setForeground(new java.awt.Color(255, 102, 102));
        jLabelNum.setText("Erreur,champ vide");

        jLabelPrenomRes.setForeground(new java.awt.Color(255, 102, 102));
        jLabelPrenomRes.setText("Erreur,champ vide");

        jLabelRelation.setForeground(new java.awt.Color(255, 102, 102));
        jLabelRelation.setText("Erreur,champ vide");

        jLabelCodePREs.setForeground(new java.awt.Color(255, 102, 102));
        jLabelCodePREs.setText("Code Postal invalide");

        jLabelEmail.setForeground(new java.awt.Color(255, 102, 102));
        jLabelEmail.setText("E-mail invalide");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(21, 21, 21)
                        .addComponent(jTextFieldNUMTEL))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldADRESSERES, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNOMRES)
                            .addComponent(jTextFieldPROFESSIONRES, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jTextFieldNCINRES))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAdrRes)
                            .addComponent(jLabelNum)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNCIN)
                            .addComponent(jLabelNomRes))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCODEPOSTALRES, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldRELATION, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldPRENOMRES, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(158, 158, 158)
                                    .addComponent(jLabelPrenomRes))
                                .addComponent(jLabelRelation, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jLabelCodePREs))))))
                .addGap(76, 76, 76))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTextFieldNCINRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNCIN))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNOMRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPRENOMRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomRes)
                    .addComponent(jLabelPrenomRes))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldPROFESSIONRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRELATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRelation))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldADRESSERES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCODEPOSTALRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdrRes)
                    .addComponent(jLabelCodePREs))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldNUMTEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNum)
                    .addComponent(jLabelEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonANNULER)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonREINITIALISER)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(jButtonENREGISTRER)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonANNULER)
                    .addComponent(jButtonREINITIALISER)
                    .addComponent(jButtonENREGISTRER))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNOMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNOMKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNOMKeyTyped

    private void jTextFieldPRENOMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPRENOMKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPRENOMKeyTyped

    private void jTextFieldADRESSEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldADRESSEKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldADRESSEKeyTyped

    private void jTextFieldNOMRESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNOMRESKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNOMRESKeyTyped

    private void jTextFieldPRENOMRESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPRENOMRESKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPRENOMRESKeyTyped

    private void jTextFieldPROFESSIONRESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPROFESSIONRESKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPROFESSIONRESKeyTyped

    private void jTextFieldRELATIONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRELATIONKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isLetter(input)&& input!=' '){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldRELATIONKeyTyped

    private void jTextFieldCODEPOSTALKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCODEPOSTALKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCODEPOSTALKeyTyped

    private void jTextFieldNCINRESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNCINRESKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNCINRESKeyTyped

    private void jTextFieldCODEPOSTALRESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCODEPOSTALRESKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCODEPOSTALRESKeyTyped

    private void jTextFieldNUMTELKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNUMTELKeyTyped
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNUMTELKeyTyped

    private void jButtonREINITIALISERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREINITIALISERActionPerformed
        // TODO add your handling code here:
            jLabelNom.setVisible(false);jLabelPrenom.setVisible(false);jLabelSexe.setVisible(false);jLabelDate.setVisible(false);
        jLabelPays.setVisible(false);jLabelAdresse.setVisible(false);jLabelNiveau.setVisible(false);jLabelCodeP.setVisible(false);
        jLabelNCIN.setVisible(false);jLabelNomRes.setVisible(false);jLabelAdrRes.setVisible(false);
        jLabelNum.setVisible(false);jLabelRelation.setVisible(false);jLabelPrenomRes.setVisible(false);
        jLabelCodePREs.setVisible(false);jLabelEmail.setVisible(false);
            jTextFieldNOM.setText("");jTextFieldPRENOM.setText("");jTextFieldADRESSE.setText("");jTextFieldCODEPOSTAL.setText("");jTextFieldNOMRES.setText("");jTextFieldPRENOMRES.setText("");jTextFieldADRESSERES.setText("");jTextFieldNUMTEL.setText("");jTextFieldEMAIL.setText("");jTextFieldCODEPOSTALRES.setText("");jTextFieldPROFESSIONRES.setText("");jTextFieldRELATION.setText("");jTextFieldNCINRES.setText("");
             jComboBoxANNEE.setSelectedIndex(0);jComboBoxMOIS.setSelectedIndex(0);jComboBoxJOUR.setSelectedIndex(0);jComboBoxNIVEAU.setSelectedIndex(0);jComboBoxPAYS.setSelectedIndex(0);jComboBoxVILLE.setSelectedIndex(0);jComboBoxsexe.setSelectedIndex(0);

    }//GEN-LAST:event_jButtonREINITIALISERActionPerformed

    private void jButtonANNULERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonANNULERActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment Quitter ?","Attention",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
		   {
			   dispose();
		   }
    }//GEN-LAST:event_jButtonANNULERActionPerformed

    private void jButtonENREGISTRERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENREGISTRERActionPerformed
        // TODO add your handling code here:
        if(jTextFieldNOM.getText().equals("")){
            jLabelNom.setVisible(true);
        }
        else jLabelNom.setVisible(false);
        
        if(jTextFieldPRENOM.getText().equals("")){
            jLabelPrenom.setVisible(true);
        }
        else jLabelPrenom.setVisible(false);
        
        if(jTextFieldADRESSE.getText().equals("")){
            jLabelAdresse.setVisible(true);
        }
        else jLabelAdresse.setVisible(false);
        
        if(jTextFieldCODEPOSTAL.getText().length()<4 && !(jTextFieldCODEPOSTAL.getText()).equals(""))
            jLabelCodeP.setVisible(true);
        else jLabelCodeP.setVisible(false);
        
        if(jTextFieldNCINRES.getText().equals("")){
            jLabelNCIN.setText("Erreur, champ vide");
            jLabelNCIN.setVisible(true);
        }
        else if(jTextFieldNCINRES.getText().length()<8)
            {jLabelNCIN.setText("N°CIN Invalide");
            jLabelNCIN.setVisible(true);}
        else jLabelNCIN.setVisible(false);
        
        if(jTextFieldNOMRES.getText().equals("")){
            jLabelNomRes.setVisible(true);
        }
        else jLabelNomRes.setVisible(false);
        
        if(jTextFieldPRENOMRES.getText().equals("")){
            jLabelPrenomRes.setVisible(true);
        }
        else jLabelPrenomRes.setVisible(false);
        
        if(jTextFieldRELATION.getText().equals("")){
            jLabelRelation.setVisible(true);
        }
        else jLabelRelation.setVisible(false);
        
        if(jTextFieldADRESSERES.getText().equals("")){
            jLabelAdrRes.setVisible(true);
        }
        else jLabelAdrRes.setVisible(false);
        
        if(jTextFieldCODEPOSTALRES.getText().length()<4 && !(jTextFieldCODEPOSTALRES.getText()).equals(""))
            jLabelCodePREs.setVisible(true);
        else jLabelCodePREs.setVisible(false);
        
        if(!Email.isValidEmailAddress(jTextFieldEMAIL.getText())&& !(jTextFieldEMAIL.getText()).equals(""))
            jLabelEmail.setVisible(true);
        else jLabelEmail.setVisible(false);
        
        if(jTextFieldNUMTEL.getText().equals("")){
            jLabelNum.setText("Erreur, champ vide");
            jLabelNum.setVisible(true);
        }
        else if(jTextFieldNUMTEL.getText().length()<8)
            {jLabelNum.setText("Num Tel invalide");
            jLabelNum.setVisible(true);}
        else jLabelNum.setVisible(false);
        
        if(jComboBoxANNEE.getSelectedIndex()==0 || jComboBoxMOIS.getSelectedIndex()==0 || jComboBoxJOUR.getSelectedIndex()==0){
            jLabelDate.setVisible(true);
        }
        else jLabelDate.setVisible(false);
        
        if(jComboBoxPAYS.getSelectedIndex()==0){
            jLabelPays.setVisible(true);
        }
        else jLabelPays.setVisible(false);
        
        if(jComboBoxNIVEAU.getSelectedIndex()==0){
            jLabelNiveau.setVisible(true);
        }
        else jLabelNiveau.setVisible(false);
        
        if(jComboBoxsexe.getSelectedIndex()==0){
            jLabelSexe.setVisible(true);
        }
        else jLabelSexe.setVisible(false);
        if(jLabelNom.isVisible()==false 
                && jLabelPrenom.isVisible()==false 
                && jLabelSexe.isVisible()==false
                && jLabelDate.isVisible()==false
                && jLabelCodeP.isVisible()==false 
                && jLabelPays.isVisible()==false 
                && jLabelAdresse.isVisible()==false 
                && jLabelNiveau.isVisible()==false 
                && jLabelNCIN.isVisible()==false 
                && jLabelNomRes.isVisible()==false 
                && jLabelAdrRes.isVisible()==false 
                && jLabelNum.isVisible()==false 
                && jLabelRelation.isVisible()==false 
                && jLabelPrenomRes.isVisible()==false 
                && jLabelCodePREs.isVisible()==false 
                && jLabelEmail.isVisible()==false ){
            Eleve e;           
            e = new Eleve(Ndoss,jTextFieldNOM.getText()
                    ,jTextFieldPRENOM.getText(),jComboBoxANNEE.getSelectedItem().toString()+"+"+jComboBoxMOIS.getSelectedItem().toString()+"+"+jComboBoxJOUR.getSelectedItem().toString()
                    ,jComboBoxsexe.getSelectedItem().toString(),jComboBoxPAYS.getSelectedItem().toString()
                    ,jComboBoxVILLE.getSelectedItem().toString(),jTextFieldADRESSE.getText(),Conversion.StringtoInt(jTextFieldCODEPOSTAL.getText())
                    ,jComboBoxNIVEAU.getSelectedItem().toString(),Conversion.StringtoInt(jTextFieldNCINRES.getText()),jTextFieldNOMRES.getText(),jTextFieldPRENOMRES.getText()
                    ,jTextFieldPROFESSIONRES.getText(),jTextFieldRELATION.getText(),jTextFieldADRESSERES.getText()
                    ,Conversion.StringtoInt(jTextFieldCODEPOSTALRES.getText()),Conversion.StringtoInt(jTextFieldNUMTEL.getText())
                    ,jTextFieldEMAIL.getText());
            if(e.ModifierEleve(Ndoss)){
                JOptionPane.showMessageDialog(null, "L'élève a été Modifié avec succes!");
                dispose();
                InterfacePrincipaleEleve.updateTableEl();
            }
            else JOptionPane.showMessageDialog(null, "Echec de modification d'élève!"); 
        }
    }//GEN-LAST:event_jButtonENREGISTRERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierEleve().setVisible(true);
            }
        });
    }

    public JComboBox<String> getjComboBoxANNEE() {
        return jComboBoxANNEE;
    }

    public JComboBox<String> getjComboBoxJOUR() {
        return jComboBoxJOUR;
    }

    public JComboBox<String> getjComboBoxMOIS() {
        return jComboBoxMOIS;
    }

    public JComboBox<String> getjComboBoxNIVEAU() {
        return jComboBoxNIVEAU;
    }

    public JComboBox<String> getjComboBoxPAYS() {
        return jComboBoxPAYS;
    }

    public JComboBox<String> getjComboBoxVILLE() {
        return jComboBoxVILLE;
    }

    public JComboBox<String> getjComboBoxsexe() {
        return jComboBoxsexe;
    }

    public JTextField getjTextFieldADRESSE() {
        return jTextFieldADRESSE;
    }

    public JTextField getjTextFieldADRESSERES() {
        return jTextFieldADRESSERES;
    }

    public JTextField getjTextFieldCODEPOSTAL() {
        return jTextFieldCODEPOSTAL;
    }

    public JTextField getjTextFieldCODEPOSTALRES() {
        return jTextFieldCODEPOSTALRES;
    }

    public JTextField getjTextFieldEMAIL() {
        return jTextFieldEMAIL;
    }

    public JTextField getjTextFieldNCINRES() {
        return jTextFieldNCINRES;
    }

    public static JTextField getjTextFieldNOM() {
        return jTextFieldNOM;
    }

    public JTextField getjTextFieldNOMRES() {
        return jTextFieldNOMRES;
    }

    public JTextField getjTextFieldNUMTEL() {
        return jTextFieldNUMTEL;
    }

    public JTextField getjTextFieldPRENOM() {
        return jTextFieldPRENOM;
    }

    public JTextField getjTextFieldPRENOMRES() {
        return jTextFieldPRENOMRES;
    }

    public JTextField getjTextFieldPROFESSIONRES() {
        return jTextFieldPROFESSIONRES;
    }

    public JTextField getjTextFieldRELATION() {
        return jTextFieldRELATION;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonANNULER;
    private javax.swing.JButton jButtonENREGISTRER;
    private javax.swing.JButton jButtonREINITIALISER;
    private javax.swing.JComboBox<String> jComboBoxANNEE;
    private javax.swing.JComboBox<String> jComboBoxJOUR;
    private javax.swing.JComboBox<String> jComboBoxMOIS;
    private javax.swing.JComboBox<String> jComboBoxNIVEAU;
    private javax.swing.JComboBox<String> jComboBoxPAYS;
    private javax.swing.JComboBox<String> jComboBoxVILLE;
    private javax.swing.JComboBox<String> jComboBoxsexe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdrRes;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelCodeP;
    private javax.swing.JLabel jLabelCodePREs;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNCIN;
    private javax.swing.JLabel jLabelNiveau;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNomRes;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelPays;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelPrenomRes;
    private javax.swing.JLabel jLabelRelation;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldADRESSE;
    private javax.swing.JTextField jTextFieldADRESSERES;
    private javax.swing.JTextField jTextFieldCODEPOSTAL;
    private javax.swing.JTextField jTextFieldCODEPOSTALRES;
    private javax.swing.JTextField jTextFieldEMAIL;
    private javax.swing.JTextField jTextFieldNCINRES;
    private static javax.swing.JTextField jTextFieldNOM;
    private javax.swing.JTextField jTextFieldNOMRES;
    private javax.swing.JTextField jTextFieldNUMTEL;
    private javax.swing.JTextField jTextFieldPRENOM;
    private javax.swing.JTextField jTextFieldPRENOMRES;
    private javax.swing.JTextField jTextFieldPROFESSIONRES;
    private javax.swing.JTextField jTextFieldRELATION;
    // End of variables declaration//GEN-END:variables
}
